WebApplication/Controllers/RolesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using WebApplication.Models;
using Microsoft.AspNetCore.Identity;
using WebApplication.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication.Helpers;
using WebApplication.Models.Extensions;

namespace WebApplication.Controllers
{
    public class RolesController : BaseController
    {
        private readonly RoleManager<Role> _roleManager;
        private readonly ILogger _logger;

        public RolesController(
            UserManager<User> userManager, RoleManager<Role> roleManager, ILoggerFactory loggerFactory, ApplicationDbContext context) : base(userManager, context)
        {
            _roleManager = roleManager;
            _logger = loggerFactory.CreateLogger<RolesController>();
        }
        
        public async Task<IActionResult> Index()
        {
            if (!HasPermission("VIEW_ROLES"))
            {
                return Unauthorized();
            }

            var roles = _roleManager.Roles;
            return View(await roles.Include(r => r.RolePermissions).ToListAsync());
        }
        
        public async Task<IActionResult> Details(int? id)
        {
            if (!HasPermission("VIEW_ROLES"))
            {
                return Unauthorized();
            }

            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.Roles.Include(r => r.RolePermissions).FirstOrDefaultAsync(r => r.Id == id);

            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }
        
        public IActionResult Create()
        {
            if (!HasPermission("CREATE_ROLES"))
            {
                return Unauthorized();
            }

            ViewBag.PermissionGroups = PermissionGroup.GetList();
            ViewBag.Permissions = _context.Permissions.ToList().ToListViewModel();
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (!HasPermission("CREATE_ROLES"))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                var role = model.ToEntity();

                var result = await _roleManager.CreateAsync(role);

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            ViewBag.PermissionGroups = PermissionGroup.GetList();
            ViewBag.Permissions = _context.Permissions.ToList().ToListViewModel();

            return View(model);
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (!HasPermission("EDIT_ROLES"))
            {
                return Unauthorized();
            }

            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.Roles.Include(r => r.RolePermissions).FirstOrDefaultAsync(r => r.Id == id.Value);

            if (role == null)
            {
                return NotFound();
            }

            ViewBag.PermissionGroups = PermissionGroup.GetList();
            ViewBag.Permissions = _context.Permissions.ToList().ToListViewModel();

            return View(role.ToViewModel());
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RoleViewModel model)
        {
            if (!HasPermission("EDIT_ROLES"))
            {
                return Unauthorized();
            }

            var role = await _roleManager.Roles.Include(r => r.RolePermissions).FirstOrDefaultAsync(r => r.Id == model.Id);

            if (role == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                role = model.UpdateEntity(role);

                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            ViewBag.PermissionGroups = PermissionGroup.GetList();
            ViewBag.Permissions = _context.Permissions.ToList().ToListViewModel();

            return View(model);
        }
        
        [ActionName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (!HasPermission("DELETE_ROLES"))
            {
                return Unauthorized();
            }

            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id.ToString());

            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!HasPermission("DELETE_ROLES"))
            {
                return Unauthorized();
            }

            var role = await _roleManager.FindByIdAsync(id.ToString());

            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Index");
        }
    }
}

WebApplication/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using WebApplication.Models;
using WebApplication.Data;
using Microsoft.EntityFrameworkCore;
using WebApplication.Models.Extensions;

namespace WebApplication.Controllers
{
    public class UsersController : BaseController
    {
        private readonly ILogger _logger;

        public UsersController(
            UserManager<User> userManager,
            ILoggerFactory loggerFactory, ApplicationDbContext context) : base(userManager, context)
        {
            _logger = loggerFactory.CreateLogger<AccountController>();
        }
        
        public async Task<IActionResult> Index()
        {
            if (!HasPermission("VIEW_USERS"))
            {
                return Unauthorized();
            }

            return View(await _userManager.Users.ToListAsync());
        }
        
        public async Task<IActionResult> Details(int? id)
        {
            if (!HasPermission("VIEW_USERS"))
            {
                return Unauthorized();
            }

            if (id == null)
            {
                return NotFound();
            }

            User user = await _userManager.FindByIdAsync(id.ToString());

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        
        public IActionResult Create()
        {
            if (!HasPermission("CREATE_USERS"))
            {
                return Unauthorized();
            }

            ViewBag.Roles = _context.Roles.ToList().ToListViewModel();

            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            if (!HasPermission("CREATE_USERS"))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                var user = model.ToEntity();

                var result = await _userManager.CreateAsync(user, model.Password);

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            ViewBag.Roles = _context.Roles.ToList().ToListViewModel();

            return View(model);
        }
        
        public async Task<IActionResult> Edit(int? id)
        {
            if (!HasPermission("EDIT_USERS"))
            {
                return Unauthorized();
            }

            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.Users.Include(u => u.Roles).FirstOrDefaultAsync(u => u.Id == id.Value);

            if (user == null)
            {
                return NotFound();
            }


            ViewBag.Roles = _context.Roles.ToList().ToListViewModel();

            return View(user.ToViewModel());
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            if (!HasPermission("EDIT_USERS"))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                var user = await _userManager.Users.Include(u => u.Roles).FirstOrDefaultAsync(u => u.Id == model.Id);

                if (user == null)
                {
                    return NotFound();
                }
                
                await _userManager.SetEmailAsync(user, model.Email);
                await _userManager.SetUserNameAsync(user, model.UserName);

                user = model.UpdateEntity(user);

                var result = await _userManager.UpdateAsync(user);

                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            ViewBag.Roles = _context.Roles.ToList().ToListViewModel();

            return View(model);
        }

        public async Task<IActionResult> ChangePassword(int? id)
        {
            if (!HasPermission("CHANGE_USERS_PASSWORDS"))
            {
                return Unauthorized();
            }

            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == id.Value);

            if (user == null)
            {
                return NotFound();
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(UserChangePasswordViewModel model)
        {
            if (!HasPermission("CHANGE_USERS_PASSWORDS"))
            {
                return Unauthorized();
            }

            if (ModelState.IsValid)
            {
                var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Id == model.Id);

                if (user == null)
                {
                    return NotFound();
                }

                await _userManager.RemovePasswordAsync(user);
                await _userManager.AddPasswordAsync(user, model.Password);

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }

            return View(model);
        }

        [ActionName("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (!HasPermission("DELETE_USERS"))
            {
                return Unauthorized();
            }

            if (id == null)
            {
                return NotFound();
            }

            User user = await _userManager.FindByIdAsync(id.ToString());
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!HasPermission("DELETE_USERS"))
            {
                return Unauthorized();
            }

            User user = await _userManager.FindByIdAsync(id.ToString());
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
    }
}

WebApplication/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Unauthorized";
}

<div class="panel mb25">
    <div class="panel-heading">
        <span>Unauthorized</span>
    </div>
    <div class="panel-body">
        <p>You are not authorized to perform this operation.</p>
    </div>
</div>

WebApplication/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"] - WebApplication</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" href="~/favicon.ico">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!-- page level plugin styles -->
    <!-- /page level plugin styles -->
    <!-- build:css({.tmp,app}) styles/app.min.css -->
    <link rel="stylesheet" href="~/vendor/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/vendor/perfect-scrollbar/css/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/styles/roboto.css">
    <link rel="stylesheet" href="~/styles/font-awesome.css">
    <link rel="stylesheet" href="~/styles/panel.css">
    <link rel="stylesheet" href="~/styles/feather.css">
    <link rel="stylesheet" href="~/styles/animate.css">
    <link rel="stylesheet" href="~/styles/urban.css">
    <link rel="stylesheet" href="~/styles/urban.skins.css">
    @RenderSection("styles", required: false)
    <!-- endbuild -->

</head>

<body>
    <div class="app layout-fixed-header">
        <!-- sidebar panel -->
        <div class="sidebar-panel offscreen-left">
            <div class="brand">
                <!-- logo -->
                <div class="brand-logo">
                    <a asp-action="Index" asp-controller="Home">
                                 WebApplication
                        @*<img src="~/images/swift.png" height="15" alt="WebApplication">*@
                    </a>
                </div>
                <!-- /logo -->
                <!-- toggle small sidebar menu -->
                <a href="javascript:;" class="toggle-sidebar hidden-xs hamburger-icon v3" data-toggle="layout-small-menu">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
                <!-- /toggle small sidebar menu -->
            </div>
            <!-- main navigation -->
            <nav role="navigation">
                <ul class="nav">
                    <!-- dashboard -->
                    <li>
                        <a asp-controller="Home" asp-action="Index"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
                    </li>
                    <li>
                        <a href="javascript:;"><i class="fa fa-wrench"></i><span>Administration</span></a>
                        <ul class="sub-menu">
                            @*<li><a asp-controller="Locations" asp-action="Index">Locations</a></li>*@
                            <li><a asp-controller="Users" asp-action="Index">Users</a></li>
                        </ul>
                    </li>
                    <!-- /administration -->
                    <!-- settings -->
                    <li>
                        <a href="javascript:;"><i class="fa fa-cogs"></i><span>Settings</span></a>
                        <ul class="sub-menu">
                            @*<li><a asp-controller="Settings" asp-action="Index"><span>General</span></a></li>*@
                            <li><a asp-controller="Roles" asp-action="Index"><span>Roles &amp; Permissions</span></a></li>
                        </ul>
                    </li>
                    <!-- /settings -->
                </ul>
            </nav>
            <!-- /main navigation -->
        </div>
        <!-- /sidebar panel -->
        <!-- content panel -->
        <div class="main-panel">
            <!-- top header -->
            <header class="header navbar">
                <div class="brand visible-xs">
                    <!-- toggle offscreen menu -->
                    <div class="toggle-offscreen">
                        <a href="#" class="hamburger-icon visible-xs" data-toggle="offscreen" data-move="ltr">
                            <span></span>
                            <span></span>
                            <span></span>
                        </a>
                    </div>
                    <!-- /toggle offscreen menu -->
                    <!-- logo -->
                    <div class="brand-logo">
                        <img src="~/images/logo-dark.png" height="15" alt="">
                    </div>
                    <!-- /logo -->
                </div>
                @if (IsSectionDefined("NavBarText"))
                {
                    <ul class="nav navbar-nav hidden-xs">
                        <li>
                            <p class="navbar-text">
                                @RenderSection("NavBarText")
                            </p>
                        </li>
                    </ul>
                }
                <ul class="nav navbar-nav navbar-right hidden-xs">
                    <li>
                        <a href="javascript:;" data-toggle="dropdown">
                            <i class="fa fa-user"></i>
                            <span>@User.Identity.Name</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a asp-controller="Manage" asp-action="ChangePassword">Change Password</a>
                            </li>
                            <li>
                                <a asp-controller="Account" asp-action="LogOff">Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </header>
            <!-- /top header -->
            <!-- main area -->
            <div class="main-content">
                @if (IsSectionDefined("Breadcrumbs"))
                {
                    RenderSection("Breadcrumbs");
                }
                @RenderBody()
            </div>
            <!-- /main area -->
        </div>
        <!-- /content panel -->
        <!-- bottom footer -->
        <footer class="content-footer">
            <nav class="footer-right">
                <ul class="nav">
                    <li>
                        <a href="javascript:;" class="scroll-up">
                            <i class="fa fa-angle-up"></i>
                        </a>
                    </li>
                </ul>
            </nav>
            <nav class="footer-left">
                <ul class="nav">
                    <li>
                        <a href="javascript:;">Copyright <i class="fa fa-copyright"></i> <span>DavidSilwal</span> 2015. All rights reserved</a>
                    </li>
                </ul>
            </nav>
        </footer>
        <!-- /bottom footer -->
    </div>
    <!-- build:js({.tmp,app}) scripts/app.min.js -->
    <script src="~/scripts/extentions/modernizr.js"></script>
    <script src="~/vendor/jquery/dist/jquery.js"></script>
    <script src="~/vendor/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/vendor/jquery.easing/jquery.easing.js"></script>
    <script src="~/vendor/fastclick/lib/fastclick.js"></script>
    <script src="~/vendor/onScreen/jquery.onscreen.js"></script>
    <script src="~/vendor/jquery-countTo/jquery.countTo.js"></script>
    <script src="~/vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
    <script src="~/scripts/ui/accordion.js"></script>
    <script src="~/scripts/ui/animate.js"></script>
    <script src="~/scripts/ui/link-transition.js"></script>
    <script src="~/scripts/ui/panel-controls.js"></script>
    <script src="~/scripts/ui/preloader.js"></script>
    <script src="~/scripts/ui/toggle.js"></script>
    <script src="~/scripts/urban-constants.js"></script>
    <script src="~/scripts/extentions/lib.js"></script>
    @RenderSection("scripts", required: false)
    <!-- endbuild -->
</body>

</html>

WebApplication/Views/Shared/_Print.cshtml
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"] - WebApplication</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" href="~/favicon.ico">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <!-- page level plugin styles -->
    <!-- /page level plugin styles -->
    <!-- build:css({.tmp,app}) styles/app.min.css -->
    <link rel="stylesheet" href="~/vendor/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/vendor/perfect-scrollbar/css/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/styles/roboto.css">
    <link rel="stylesheet" href="~/styles/font-awesome.css">
    <link rel="stylesheet" href="~/styles/panel.css">
    <link rel="stylesheet" href="~/styles/feather.css">
    <link rel="stylesheet" href="~/styles/animate.css">
    <link rel="stylesheet" href="~/styles/urban.css">
    <link rel="stylesheet" href="~/styles/urban.skins.css">
    @RenderSection("styles", required: false)
    <!-- endbuild -->

</head>

<body>

    <div class="col-lg-12">
        <div class="row mb30">
            <div class="panel panel-default">
                <div class="panel-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    <!-- build:js({.tmp,app}) scripts/app.min.js -->
    <script src="~/scripts/extentions/modernizr.js"></script>
    <script src="~/vendor/jquery/dist/jquery.js"></script>
    <script src="~/vendor/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/vendor/jquery.easing/jquery.easing.js"></script>
    <script src="~/vendor/fastclick/lib/fastclick.js"></script>
    <script src="~/vendor/onScreen/jquery.onscreen.js"></script>
    <script src="~/vendor/jquery-countTo/jquery.countTo.js"></script>
    <script src="~/vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
    <script src="~/scripts/ui/accordion.js"></script>
    <script src="~/scripts/ui/animate.js"></script>
    <script src="~/scripts/ui/link-transition.js"></script>
    <script src="~/scripts/ui/panel-controls.js"></script>
    <script src="~/scripts/ui/preloader.js"></script>
    <script src="~/scripts/ui/toggle.js"></script>
    <script src="~/scripts/urban-constants.js"></script>
    <script src="~/scripts/extentions/lib.js"></script>
    @RenderSection("scripts", required: false)
    <!-- endbuild -->
</body>

</html>

WebApplication/Views/Shared/_PrintLite.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="~/print/resources/css/animate.css">
    <link rel="stylesheet" type="text/css" href="~/print/resources/css/default.css">
    <link rel="stylesheet" href="~/print/resources/css/devicon.min.css">
</head>
<body>
@RenderBody()
</body>
</html>

WebApplication/Views/Shared/_Session.cshtml
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
    <title>@ViewData["Title"] - WebApplication</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <link rel="shortcut icon" href="~/favicon.ico">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

  <!-- page level plugin styles -->
  <!-- /page level plugin styles -->

  <!-- build:css({.tmp,app}) styles/app.min.css -->
  <link rel="stylesheet" href="~/vendor/bootstrap/dist/css/bootstrap.css">
  <link rel="stylesheet" href="~/vendor/perfect-scrollbar/css/perfect-scrollbar.css">
  <link rel="stylesheet" href="~/styles/roboto.css">
  <link rel="stylesheet" href="~/styles/font-awesome.css">
  <link rel="stylesheet" href="~/styles/panel.css">
  <link rel="stylesheet" href="~/styles/feather.css">
  <link rel="stylesheet" href="~/styles/animate.css">
  <link rel="stylesheet" href="~/styles/urban.css">
  <link rel="stylesheet" href="~/styles/urban.skins.css">
    <style type="text/css">
        body {
            background-image: url("/images/map.jpg");
            background-size: contain;
            background-position: top center;
        }
    </style>
  @RenderSection("styles", required: false)
  <!-- endbuild -->

</head>

<body>

  <div class="layout-fixed-header usersession">
    <div class="full-height">
      <div class="center-wrapper">
        <div class="center-content">
          <div class="row no-margin">
            @RenderBody()
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- build:js({.tmp,app}) scripts/app.min.js -->
  <script src="~/scripts/extentions/modernizr.js"></script>
  <script src="~/vendor/jquery/dist/jquery.js"></script>
  <script src="~/vendor/bootstrap/dist/js/bootstrap.js"></script>
  <script src="~/vendor/jquery.easing/jquery.easing.js"></script>
  <script src="~/vendor/fastclick/lib/fastclick.js"></script>
  <script src="~/vendor/onScreen/jquery.onscreen.js"></script>
  <script src="~/vendor/jquery-countTo/jquery.countTo.js"></script>
  <script src="~/vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
  <script src="~/scripts/ui/accordion.js"></script>
  <script src="~/scripts/ui/animate.js"></script>
  <script src="~/scripts/ui/link-transition.js"></script>
  <script src="~/scripts/ui/panel-controls.js"></script>
  <script src="~/scripts/ui/preloader.js"></script>
  <script src="~/scripts/ui/toggle.js"></script>
  <script src="~/scripts/urban-constants.js"></script>
  <script src="~/scripts/extentions/lib.js"></script>
    @RenderSection("scripts", required: false)
  <!-- endbuild -->
</body>

</html>